--- 
AllowedHosts: "*"
BlobStorageSettings: 
  ServiceAccount: 
    clientId: c2b13159-110b-4705-bd3b-d0dac62ae6c4
    clientSecret: 591af1eacc3b308cde64326de812662ebd217e811e95e6f13c3b92f1e401d350
    storageAccountName: ssdd1weubstsupdigplat002
    tenantId: 35595a02-4d6d-44ac-99e1-f9ab4cd872db
  connectionString: DefaultEndpointsProtocol=https;AccountName=statetfdev;AccountKey=GraadyPMXe155OmwxpxJBCMVCTx46hemVIQZ3gDWj6gFn5TGSNmDUj1p/DUmiBteKdLCmkx3C82IJO47gQ/WZA==;EndpointSuffix=core.windows.net
  containerName: customer-service-dev
  isPrivate: false
IdentityManagerSettings: 
  Authority: "http://user-service.n5.svc.cluster.local:8080"
ImageSettings: 
  compressionLevel: 9
  mediumSize: 210
  microSize: 50
  signatureWidth: 600
Kestrel: 
  EndPoints: 
    Http: 
      Url: "http://*:8080"
OrchestratorType: K8S
Serilog: 
  Enrich: 
    - WithExceptionDetails
  MinimumLevel: 
    Default: Verbose
    Override: 
      Microsoft.AspNetCore.Hosting.Diagnostics: Warning
      Microsoft.AspNetCore.Routing: Warning
      Microsoft.AspNetCore.Server.Kestrel: Warning
      Microsoft.EntityFrameworkCore.Infrastructure: Warning
      Microsoft.Hosting.Lifetime: Information
  Using: 
    - Serilog.Sinks.Debug
  WriteTo: 
    - 
      Args: 
        outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}"
        theme: "Serilog.Sinks.SystemConsole.Themes.AnsiConsoleTheme::Code, Serilog.Sinks.Console"
      Name: Console
    - 
      Args: 
        indexFormat: "logs-customer-{0:yyyy.MM}"
        nodeUris: "http://elastic:5ib9lkwB165f705MnV9hvRc8@elasticsearch-n5-es-http.elastic-system.svc.cluster.local:9200"
        templateName: myCustomTemplate
      Name: Elasticsearch
connectionString: "Server=tcp:n5-dev.database.windows.net,1433;Initial Catalog=customer-db;Persist Security Info=False;User ID=encinco;Password=3Qf=LW`mn>%es=A'a)CrYm[f;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
culture: 
  language: es-ES
  moneySymbol: $
elasticSearch: 
  endpointUri: "http://elastic:5ib9lkwB165f705MnV9hvRc8@elasticsearch-n5-es-http.elastic-system.svc.cluster.local:9200"
  index: 
    customer: customer
healthUrl: /probandoJP
kafka: 
  busUrl: "n5-kafka-dev.southcentralus.cloudapp.azure.com:9094"
  consumerConfig: 
    fetch.error.backoff.ms: 1
    socket.blocking.max.ms: 1
    socket.nagle.disable: true
    statistics.interval.ms: 60000
  producerConfig: 
    queue.buffering.max.ms: 1
    socket.blocking.max.ms: 1
    socket.nagle.disable: true
  topics: 
    domain: 
      group: customer_service_cf6094e9-be7b-4805-af28-3bd29c5f2e5b
      name: customers_domain
    external: 
      group: customer_service_cf6094e9-be7b-4805-af28-3bd29c5f2e5b
      name: customers_external
    integration: 
      group: customer_service_cf6094e9-be7b-4805-af28-3bd29c5f2e5b
      name: customers_integrations
reservedFieldNames: 
  customerIds: customerIds
  specialRateRequest: specialRateRequest
translator: 
  gender: 
    FEMALE: F
    MALE: M
urls: "http://*:8080"
